### ISSUE TITLE
Unable to install via conda

### ISSUE THREAD

**Issue by santoshe1** [borenstein-lab/MetaLAFFA#6]
Hello,

I am trying to install metalaffa via conda using conda

**conda create -n metalaffa metalaffa -c bioconda -c borenstein-lab -y**

There is no response even after ~12hours, the command shows Solving environment and nothing further happens.

Any other ways to install the tool?

Thank you

**Comment by engal** [comment]
Conda is the primary way to install the tool, otherwise you'll have to handle manually installing the third-party tools that MetaLAFFA relies on. One possibility for the long solving time is that you may have the conda-forge channel turned on by default. This channel contains a large number of packages that the solver has to consider, but it is not required for the initial installation of MetaLAFFA. You can check to see if conda-forge is turned on by default by looking at your ~/.condarc file. If conda-forge is there, you can try removing it and retrying the MetaLAFFA installation.

If this is not the case, then you can try creating the environment by installing dependencies in stages. You'll need to start with
`conda create -n metalaffa python=3.6.10`
and then try installing the rest of the dependencies one or more at a time. You can find the explicit dependencies and their required versions in the meta.yaml file under the 'requirements' section.

**Comment by santoshe1** [comment]
Issue is resolved. Thank you for the support!
